# 1. C?u hình Server
server.port=8080

# 2. C?u hình Redis (Ch?y Docker ? c?ng 6379)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# 3. C?u hình Database H2 (ch?y ng?m trong b? nh?)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 4. B?t log SQL ra Console ?? ki?m tra truy v?n
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truese